const LDOCE_DOMAIN: string = 'https://www.ldoceonline.com';
const API_LDOCE_DOMAIN: string = 'https://api.pearson.com';
const LDOCE_SEARCH: string = `/dictionary/`;
const HEADWORD_METHOD_REQUEST_ERROR =
	'ERROR-requestRawLdoceDataByHeadwordMethod';
const HEADWORD_ID_REQUEST_ERROR = 'ERROR-makeRequestByHeadwordId';
const SEARCH_ERROR = 'ERROR-search';
const BRITAIN_SPEAKER_EXAMPLE = 'BRITAIN_SPEAKER_EXAMPLE';
const BRITAIN_SPEAKER_HEADWORD = 'BRITAIN_SPEAKER_HEADWORD';
export {
	BRITAIN_SPEAKER_EXAMPLE,
	BRITAIN_SPEAKER_HEADWORD,
	LDOCE_DOMAIN,
	LDOCE_SEARCH,
	API_LDOCE_DOMAIN,
	HEADWORD_METHOD_REQUEST_ERROR,
	HEADWORD_ID_REQUEST_ERROR,
	SEARCH_ERROR
};
